#!/usr/bin/env ruby

require_relative 'connection'

DB_NAME = 'sql_lessons'

return drop_db(DB_NAME) if !ARGV.include?('createdb') && ARGV.include?('dropdb')

drop_db(DB_NAME) if ARGV.include?('dropdb')
create_db(DB_NAME) if ARGV.include?('createdb')

connect(DB_NAME)

run_script('create_procedures')

return run_console if ARGV.include?('console') || ARGV.include?('c')

run_script('create_tables')
run_script('insert_values')